// Code generated by protoc-gen-go. DO NOT EDIT.
// source: barry.proto

package go_barry_protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BarryTest struct {
	Messagetype          *int32   `protobuf:"varint,1,req,name=messagetype,def=0" json:"messagetype,omitempty"`
	Version              *int32   `protobuf:"varint,2,req,name=version,def=1" json:"version,omitempty"`
	Timestamp            *int64   `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	Value                *int64   `protobuf:"varint,4,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BarryTest) Reset()         { *m = BarryTest{} }
func (m *BarryTest) String() string { return proto.CompactTextString(m) }
func (*BarryTest) ProtoMessage()    {}
func (*BarryTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_706b1ab586698632, []int{0}
}

func (m *BarryTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BarryTest.Unmarshal(m, b)
}
func (m *BarryTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BarryTest.Marshal(b, m, deterministic)
}
func (m *BarryTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BarryTest.Merge(m, src)
}
func (m *BarryTest) XXX_Size() int {
	return xxx_messageInfo_BarryTest.Size(m)
}
func (m *BarryTest) XXX_DiscardUnknown() {
	xxx_messageInfo_BarryTest.DiscardUnknown(m)
}

var xxx_messageInfo_BarryTest proto.InternalMessageInfo

const Default_BarryTest_Messagetype int32 = 0
const Default_BarryTest_Version int32 = 1

func (m *BarryTest) GetMessagetype() int32 {
	if m != nil && m.Messagetype != nil {
		return *m.Messagetype
	}
	return Default_BarryTest_Messagetype
}

func (m *BarryTest) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_BarryTest_Version
}

func (m *BarryTest) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *BarryTest) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*BarryTest)(nil), "go_barry_protodef.BarryTest")
}

func init() { proto.RegisterFile("barry.proto", fileDescriptor_706b1ab586698632) }

var fileDescriptor_706b1ab586698632 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4a, 0x2c, 0x2a,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0xcf, 0x8f, 0x07, 0xf3, 0xe3, 0xc1,
	0xfc, 0x94, 0xd4, 0x34, 0xa5, 0x46, 0x46, 0x2e, 0x4e, 0x27, 0x90, 0x50, 0x48, 0x6a, 0x71, 0x89,
	0x90, 0x32, 0x17, 0x77, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0x6a, 0x49, 0x65, 0x41, 0xaa, 0x04,
	0xa3, 0x02, 0x93, 0x06, 0xab, 0x15, 0xa3, 0x41, 0x10, 0xb2, 0xa8, 0x90, 0x34, 0x17, 0x7b, 0x59,
	0x6a, 0x51, 0x71, 0x66, 0x7e, 0x9e, 0x04, 0x13, 0x44, 0x81, 0x61, 0x10, 0x4c, 0x44, 0x48, 0x86,
	0x8b, 0xb3, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x40, 0x82, 0x59, 0x81, 0x49, 0x83,
	0x39, 0x08, 0x21, 0x20, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0xa2, 0xc0,
	0xa8, 0xc1, 0x1c, 0x04, 0xe1, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x52, 0xb8, 0x6d, 0x8e, 0xa4,
	0x00, 0x00, 0x00,
}
